package com.example.tradingeconomics.utils

object Constants {

    const val LOADING_SCREEN = "loading_screen"
    const val MAIN_CONTENT_SCREEN = "main_content_screen"
    const val TRY_AGAIN_SCREEN = "try_again_screen"

    // Market
    const val STOCK_SECTION = "stock_section"
    const val CURRENCY_SECTION = "currency_section"
    const val COMMODITY_SECTION = "commodity_section"
    const val BOND_SECTION = "bond_section"

    fun getCountryCode(country: String):String{
        val codes = mapOf("ad" to "Andorra",
            "ae" to "United Arab Emirates",
            "af" to "Afghanistan",
            "ag" to "Antigua and Barbuda",
            "ai" to "Anguilla",
            "al" to "Albania",
            "am" to "Armenia",
            "ao" to "Angola",
            "aq" to "Antarctica",
            "ar" to "Argentina",
            "as" to "American Samoa",
            "at" to "Austria",
            "au" to "Australia",
            "aw" to "Aruba",
            "ax" to "Åland Islands",
            "az" to "Azerbaijan",
            "ba" to "Bosnia and Herzegovina",
            "bb" to "Barbados",
            "bd" to "Bangladesh",
            "be" to "Belgium",
            "bf" to "Burkina Faso",
            "bg" to "Bulgaria",
            "bh" to "Bahrain",
            "bi" to "Burundi",
            "bj" to "Benin",
            "bl" to "Saint Barthélemy",
            "bm" to "Bermuda",
            "bn" to "Brunei",
            "bo" to "Bolivia",
            "bq" to "Caribbean Netherlands",
            "br" to "Brazil",
            "bs" to "Bahamas",
            "bt" to "Bhutan",
            "bv" to "Bouvet Island",
            "bw" to "Botswana",
            "by" to "Belarus",
            "bz" to "Belize",
            "ca" to "Canada",
            "cc" to "Cocos (Keeling) Islands",
            "cd" to "DR Congo",
            "cf" to "Central African Republic",
            "cg" to "Republic of the Congo",
            "ch" to "Switzerland",
            "ci" to "Côte d'Ivoire (Ivory Coast)",
            "ck" to "Cook Islands",
            "cl" to   "Chile",
            "cm" to "Cameroon",
            "cn" to "China",
            "co" to "Colombia",
            "cr" to "Costa Rica",
            "cu" to "Cuba",
            "cv" to "Cape Verde",
            "cw" to "Curaçao",
            "cx" to "Christmas Island",
            "cy" to "Cyprus",
            "cz" to "Czechia",
            "de" to "Germany",
            "dj" to "Djibouti",
            "dk" to "Denmark",
            "dm" to "Dominica",
            "do" to "Dominican Republic",
            "dz" to "Algeria",
            "ec" to "Ecuador",
            "ee" to "Estonia",
            "eg" to "Egypt",
            "eh" to "Western Sahara",
            "er" to "Eritrea",
            "es" to "Spain",
            "et" to "Ethiopia",
            "eu" to "European Union",
            "fi" to "Finland",
            "fj" to "Fiji",
            "fk" to "Falkland Islands",
            "fm" to "Micronesia",
            "fo" to "Faroe Islands",
            "fr" to "France",
            "ga" to "Gabon",
            "gb" to "United Kingdom",
            "gb-eng" to "England",
            "gb-nir" to "Northern Ireland",
            "gb-sct" to "Scotland",
            "gb-wls" to "Wales",
            "gd" to "Grenada",
            "ge" to "Georgia",
            "gf" to "French Guiana",
            "gg" to "Guernsey",
            "gh" to "Ghana",
            "gi" to "Gibraltar",
            "gl" to "Greenland",
            "gm" to "Gambia",
            "gn" to "Guinea",
            "gp" to "Guadeloupe",
            "gq" to "Equatorial Guinea",
            "gr" to "Greece",
            "gs" to "South Georgia",
            "gt" to "Guatemala",
            "gu" to "Guam",
            "gw" to "Guinea-Bissau",
            "gy" to "Guyana",
            "hk" to "Hong Kong",
            "hm" to "Heard Island and McDonald Islands",
            "hn" to "Honduras",
            "hr" to "Croatia",
            "ht" to "Haiti",
            "hu" to "Hungary",
            "id" to "Indonesia",
            "ie" to "Ireland",
            "il" to "Israel",
            "im" to "Isle of Man",
            "in" to "India",
            "io" to "British Indian Ocean Territory",
            "iq" to "Iraq",
            "ir" to "Iran",
            "is" to "Iceland",
            "it" to "Italy",
            "je" to "Jersey",
            "jm" to "Jamaica",
            "jo" to "Jordan",
            "jp" to "Japan",
            "ke" to "Kenya",
            "kg" to "Kyrgyzstan",
            "kh" to "Cambodia",
            "ki" to "Kiribati",
            "km" to "Comoros",
            "kn" to "Saint Kitts and Nevis",
            "kp" to "North Korea",
            "kr" to "South Korea",
            "kw" to "Kuwait",
            "ky" to "Cayman Islands",
            "kz" to "Kazakhstan",
            "la" to "Laos",
            "lb" to "Lebanon",
            "lc" to "Saint Lucia",
            "li" to "Liechtenstein",
            "lk" to "Sri Lanka",
            "lr" to "Liberia",
            "ls" to "Lesotho",
            "lt" to "Lithuania",
            "lu" to "Luxembourg",
            "lv" to "Latvia",
            "ly" to "Libya",
            "ma" to "Morocco",
            "mc" to "Monaco",
            "md" to "Moldova",
            "me" to "Montenegro",
            "mf" to "Saint Martin",
            "mg" to "Madagascar",
            "mh" to "Marshall Islands",
            "mk" to "North Macedonia",
            "ml" to "Mali",
            "mm" to "Myanmar",
            "mn" to "Mongolia",
            "mo" to "Macau",
            "mp" to "Northern Mariana Islands",
            "mq" to "Martinique",
            "mr" to "Mauritania",
            "ms" to "Montserrat",
            "mt" to "Malta",
            "mu" to "Mauritius",
            "mv" to "Maldives",
            "mw" to "Malawi",
            "mx" to "Mexico",
            "my" to "Malaysia",
            "mz" to "Mozambique",
            "na" to "Namibia",
            "nc" to "New Caledonia",
            "ne" to "Niger",
            "nf" to "Norfolk Island",
            "ng" to "Nigeria",
            "ni" to "Nicaragua",
            "nl" to "Netherlands",
            "no" to "Norway",
            "np" to "Nepal",
            "nr" to "Nauru",
            "nu" to "Niue",
            "nz" to "New Zealand",
            "om" to "Oman",
            "pa" to "Panama",
            "pe" to "Peru",
            "pf" to "French Polynesia",
            "pg" to "Papua New Guinea",
            "ph" to "Philippines",
            "pk" to "Pakistan",
            "pl" to "Poland",
            "pm" to "Saint Pierre and Miquelon",
            "pn" to "Pitcairn Islands",
            "pr" to "Puerto Rico",
            "ps" to "Palestine",
            "pt" to "Portugal",
            "pw" to "Palau",
            "py" to "Paraguay",
            "qa" to "Qatar",
            "re" to "Réunion",
            "ro" to "Romania",
            "rs" to  "Serbia",
            "ru" to   "Russia",
            "rw" to  "Rwanda",
            "sa" to   "Saudi Arabia",
            "sb" to "Solomon Islands",
            "sc" to "Seychelles",
            "sd" to "Sudan",
            "se" to "Sweden",
            "sg" to "Singapore",
            "sh" to "Saint Helena, Ascension and Tristan da Cunha",
            "si" to "Slovenia",
            "sj" to "Svalbard and Jan Mayen",
            "sk" to "Slovakia",
            "sl" to "Sierra Leone",
            "sm" to "San Marino",
            "sn" to "Senegal",
            "so" to "Somalia",
            "sr" to "Suriname",
            "ss" to "South Sudan",
            "st" to "São Tomé and Príncipe",
            "sv" to "El Salvador",
            "sx" to "Sint Maarten",
            "sy" to  "Syria",
            "sz" to "Eswatini (Swaziland)",
            "tc" to "Turks and Caicos Islands",
            "td" to  "Chad",
            "tf" to "French Southern and Antarctic Lands",
            "tg" to "Togo",
            "th" to "Thailand",
            "tj" to "Tajikistan",
            "tk" to "Tokelau",
            "tl" to "Timor-Leste",
            "tm" to "Turkmenistan",
            "tn" to "Tunisia",
            "to" to "Tonga",
            "tr" to "Turkey",
            "tt" to "Trinidad and Tobago",
            "tv" to "Tuvalu",
            "tw" to "Taiwan",
            "tz" to "Tanzania",
            "ua" to "Ukraine",
            "ug" to "Uganda",
            "um" to "United States Minor Outlying Islands",
            "un" to "United Nations",
            "us" to "United States",
            "us-ak" to "Alaska",
            "us-al" to "Alabama",
            "us-ar" to "Arkansas",
            "us-az" to "Arizona",
            "us-ca" to "California",
            "us-co" to "Colorado",
            "us-ct" to "Connecticut",
            "us-de" to "Delaware",
            "us-fl" to "Florida",
            "us-ga" to "Georgia",
            "us-hi" to "Hawaii",
            "us-ia" to "Iowa",
            "us-id" to "Idaho",
            "us-il" to "Illinois",
            "us-in" to "Indiana",
            "us-ks" to "Kansas",
            "us-ky" to "Kentucky",
            "us-la" to "Louisiana",
            "us-ma" to "Massachusetts",
            "us-md" to "Maryland",
            "us-me" to "Maine",
            "us-mi" to "Michigan",
            "us-mn" to "Minnesota",
            "us-mo" to "Missouri",
            "us-ms" to "Mississippi",
            "us-mt" to "Montana",
            "us-nc" to "North Carolina",
            "us-nd" to "North Dakota",
            "us-ne" to "Nebraska",
            "us-nh" to "New Hampshire",
            "us-nj" to "New Jersey",
            "us-nm" to "New Mexico",
            "us-nv" to "Nevada",
            "us-ny" to "New York",
            "us-oh" to "Ohio",
            "us-ok" to "Oklahoma",
            "us-or" to "Oregon",
            "us-pa" to "Pennsylvania",
            "us-ri" to "Rhode Island",
            "us-sc" to "South Carolina",
            "us-sd" to "South Dakota",
            "us-tn" to "Tennessee",
            "us-tx" to "Texas",
            "us-ut" to "Utah",
            "us-va" to "Virginia",
            "us-vt" to "Vermont",
            "us-wa" to "Washington",
            "us-wi" to "Wisconsin",
            "us-wv" to "West Virginia",
            "us-wy" to "Wyoming",
            "uy" to "Uruguay",
            "uz" to "Uzbekistan",
            "va" to "Vatican City (Holy See)",
            "vc" to "Saint Vincent and the Grenadines",
            "ve" to "Venezuela",
            "vg" to "British Virgin Islands",
            "vi" to "United States Virgin Islands",
            "vn" to "Vietnam",
            "vu" to "Vanuatu",
            "wf" to "Wallis and Futuna",
            "ws" to "Samoa",
            "xk" to "Kosovo",
            "ye" to "Yemen",
            "yt" to "Mayotte",
            "za" to "South Africa",
            "zm" to "Zambia",
            "zw" to "Zimbabwe"

        )
        val reverseCodes = codes.entries.associateBy({it.value}){it.key}

        return reverseCodes[country] ?: ""
    }
}